{/* <div className="grid h-screen grid-cols-5 text-5xl text-white">
        <motion.div 
            variants={loaderVariants}
            initial="initial"
            animate="animate"
            className='bg-blue-400'
            custom={1}
        >
        </motion.div>
        <motion.div 
            variants={loaderVariants}
            initial="initial"
            animate="animate"
            className='bg-blue-400'
            custom={2}
        >
        </motion.div>
        <motion.div 
            variants={loaderVariants}
            initial="initial"
            animate="animate"
            className='bg-blue-400'
            custom={3}
        >
        </motion.div>
        <motion.div 
            variants={loaderVariants}
            initial="initial"
            animate="animate"
            className='bg-blue-400'
            custom={4}
        >  
        </motion.div>
        <motion.div 
            variants={loaderVariants}
            initial="initial"
            animate="animate"
            className='bg-blue-400'
            custom={5}
        >
        </motion.div>
    </div> */}